apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: app1

spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: temp-content
          mountPath: /usr/share/nginx/html
  volumes:
    - name: temp-content
      emptyDir: {}
