apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pvc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pvc
  template:
    metadata:
      labels:
        app: nginx-pvc
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: my-storage
              mountPath: /usr/share/nginx/html   # Nginx default HTML root
      volumes:
        - name: my-storage
          persistentVolumeClaim:
            claimName: manual-pvc